/**
 * Comprehensive language code to name mapping for movie languages
 * Based on ISO 639-1 and ISO 639-3 language codes used globally
 * Includes languages from all continents and major language families
 */
export const LANGUAGE_MAPPING = {
  // Major International Languages
  'en': 'English',
  'es': 'Spanish',
  'fr': 'French',
  'de': 'German',
  'it': 'Italian',
  'pt': 'Portuguese',
  'ru': 'Russian',
  'ja': 'Japanese',
  'ko': 'Korean',
  'zh': 'Chinese (Mandarin)',
  'ar': 'Arabic',
  'hi': 'Hindi',
  
  // European Languages
  'nl': 'Dutch',
  'sv': 'Swedish',
  'da': 'Danish',
  'no': 'Norwegian',
  'fi': 'Finnish',
  'is': 'Icelandic',
  'fo': 'Faroese',
  'pl': 'Polish',
  'cs': 'Czech',
  'sk': 'Slovak',
  'hu': 'Hungarian',
  'ro': 'Romanian',
  'bg': 'Bulgarian',
  'hr': 'Croatian',
  'sr': 'Serbian',
  'bs': 'Bosnian',
  'mk': 'Macedonian',
  'sl': 'Slovenian',
  'mt': 'Maltese',
  'et': 'Estonian',
  'lv': 'Latvian',
  'lt': 'Lithuanian',
  'be': 'Belarusian',
  'uk': 'Ukrainian',
  'el': 'Greek',
  'sq': 'Albanian',
  'eu': 'Basque',
  'ca': 'Catalan',
  'gl': 'Galician',
  'cy': 'Welsh',
  'ga': 'Irish',
  'gd': 'Scottish Gaelic',
  'br': 'Breton',
  'co': 'Corsican',
  'rm': 'Romansh',
  'fy': 'Frisian',
  'lb': 'Luxembourgish',
  'li': 'Limburgish',
  'wa': 'Walloon',
  'sc': 'Sardinian',
  'vec': 'Venetian',
  'nap': 'Neapolitan',
  'scn': 'Sicilian',
  
  // Asian Languages - East Asia
  'yue': 'Chinese (Cantonese)',
  'nan': 'Chinese (Min Nan)',
  'wuu': 'Chinese (Wu)',
  'hsn': 'Chinese (Xiang)',
  'hak': 'Chinese (Hakka)',
  'gan': 'Chinese (Gan)',
  'mnp': 'Chinese (Min Bei)',
  'cjy': 'Chinese (Jin)',
  'cpx': 'Chinese (Pu-Xian)',
  'czh': 'Chinese (Huizhou)',
  'czo': 'Chinese (Min Zhong)',
  'mn': 'Mongolian',
  'bo': 'Tibetan',
  'dz': 'Dzongkha',
  'my': 'Myanmar (Burmese)',
  'th': 'Thai',
  'lo': 'Lao',
  'km': 'Khmer (Cambodian)',
  'vi': 'Vietnamese',
  
  // Asian Languages - South Asia
  'bn': 'Bengali',
  'as': 'Assamese',
  'or': 'Odia',
  'ta': 'Tamil',
  'te': 'Telugu',
  'kn': 'Kannada',
  'ml': 'Malayalam',
  'si': 'Sinhala',
  'gu': 'Gujarati',
  'pa': 'Punjabi',
  'mr': 'Marathi',
  'ne': 'Nepali',
  'ur': 'Urdu',
  'sd': 'Sindhi',
  'ks': 'Kashmiri',
  'doi': 'Dogri',
  'mai': 'Maithili',
  'bho': 'Bhojpuri',
  'mag': 'Magahi',
  'new': 'Newari',
  'bpy': 'Bishnupriya Manipuri',
  'sat': 'Santali',
  'gom': 'Goan Konkani',
  'kok': 'Konkani',
  'sa': 'Sanskrit',
  'pi': 'Pali',
  'dv': 'Divehi (Maldivian)',
  
  // Asian Languages - Southeast Asia
  'id': 'Indonesian',
  'ms': 'Malay',
  'tl': 'Filipino (Tagalog)',
  'ceb': 'Cebuano',
  'war': 'Waray',
  'hil': 'Hiligaynon',
  'bcl': 'Bikol',
  'pam': 'Kapampangan',
  'pag': 'Pangasinan',
  'jv': 'Javanese',
  'su': 'Sundanese',
  'mad': 'Madurese',
  'ban': 'Balinese',
  'min': 'Minangkabau',
  'bug': 'Buginese',
  'mak': 'Makasar',
  'tet': 'Tetum',
  
  // Asian Languages - West/Central Asia
  'tr': 'Turkish',
  'az': 'Azerbaijani',
  'kk': 'Kazakh',
  'ky': 'Kyrgyz',
  'uz': 'Uzbek',
  'tk': 'Turkmen',
  'tt': 'Tatar',
  'ba': 'Bashkir',
  'cv': 'Chuvash',
  'sah': 'Sakha (Yakut)',
  'tyv': 'Tuvan',
  'kjh': 'Khakas',
  'alt': 'Altai',
  'tg': 'Tajik',
  'fa': 'Persian (Farsi)',
  'ps': 'Pashto',
  'ku': 'Kurdish',
  'ckb': 'Central Kurdish (Sorani)',
  'kmr': 'Northern Kurdish (Kurmanji)',
  'sdh': 'Southern Kurdish',
  'lrc': 'Northern Luri',
  'bqi': 'Bakhtiari',
  'glk': 'Gilaki',
  'mzn': 'Mazandarani',
  'ka': 'Georgian',
  'hy': 'Armenian',
  'he': 'Hebrew',
  'yi': 'Yiddish',
  'lad': 'Ladino',
  'syc': 'Classical Syriac',
  'arc': 'Aramaic',
  
  // African Languages
  'sw': 'Swahili',
  'zu': 'Zulu',
  'xh': 'Xhosa',
  'af': 'Afrikaans',
  'st': 'Southern Sotho',
  'nso': 'Northern Sotho',
  'tn': 'Tswana',
  'ss': 'Swazi',
  'ts': 'Tsonga',
  've': 'Venda',
  'nr': 'Southern Ndebele',
  'nd': 'Northern Ndebele',
  'yo': 'Yoruba',
  'ig': 'Igbo',
  'ha': 'Hausa',
  'ff': 'Fulah',
  'wo': 'Wolof',
  'sn': 'Shona',
  'ny': 'Chichewa',
  'rw': 'Kinyarwanda',
  'rn': 'Kirundi',
  'lg': 'Luganda',
  'ki': 'Kikuyu',
  'luo': 'Luo',
  'kam': 'Kamba',
  'mer': 'Meru',
  'luy': 'Luhya',
  'kln': 'Kalenjin',
  'mas': 'Maasai',
  'so': 'Somali',
  'om': 'Oromo',
  'am': 'Amharic',
  'ti': 'Tigrinya',
  'aa': 'Afar',
  'sid': 'Sidamo',
  'wal': 'Wolaytta',
  'gez': 'Geez',
  'byn': 'Bilin',
  'tig': 'Tigre',
  'bem': 'Bemba',
  'loz': 'Lozi',
  'umb': 'Umbundu',
  'kmb': 'Kimbundu',
  'ln': 'Lingala',
  'kg': 'Kongo',
  'lua': 'Luba-Kasai',
  'lub': 'Luba-Katanga',
  'sg': 'Sango',
  'ak': 'Akan',
  'tw': 'Twi',
  'ee': 'Ewe',
  'gaa': 'Ga',
  'dag': 'Dagbani',
  'kpo': 'Kpelle',
  'men': 'Mende',
  'tem': 'Temne',
  'kr': 'Kanuri',
  'fuv': 'Nigerian Fulfulde',
  'tiv': 'Tiv',
  'bin': 'Bini',
  'ibb': 'Ibibio',
  'ann': 'Obolo',
  'efi': 'Efik',
  'mdh': 'Maguindanaon',
  'mrw': 'Maranao',
  
  // Native American Languages
  'nv': 'Navajo',
  'chr': 'Cherokee',
  'lkt': 'Lakota',
  'dak': 'Dakota',
  'oj': 'Ojibwe',
  'cr': 'Cree',
  'iu': 'Inuktitut',
  'ik': 'Inupiaq',
  'kl': 'Kalaallisut (Greenlandic)',
  'qu': 'Quechua',
  'ay': 'Aymara',
  'gn': 'Guarani',
  'nah': 'Nahuatl',
  'myn': 'Mayan',
  'yua': 'Yucatec Maya',
  'tzo': 'Tzotzil',
  'tzj': 'Tz\'utujil',
  'cak': 'Kaqchikel',
  'quc': 'K\'iche\'',
  'mam': 'Mam',
  'ixl': 'Ixil',
  'kek': 'Q\'eqchi\'',
  'poh': 'Poqomchi\'',
  'poq': 'Poqomam',
  'ach': 'Acoli',
  'lgg': 'Lugbara',
  
  // Pacific Languages
  'mi': 'Māori',
  'sm': 'Samoan',
  'to': 'Tongan',
  'fj': 'Fijian',
  'haw': 'Hawaiian',
  'ty': 'Tahitian',
  'ch': 'Chamorro',
  'mh': 'Marshallese',
  'na': 'Nauru',
  'gil': 'Gilbertese',
  'tvl': 'Tuvaluan',
  'niu': 'Niuean',
  'tkl': 'Tokelauan',
  'pwn': 'Paiwan',
  'ami': 'Amis',
  'tay': 'Atayal',
  'ssf': 'Thao',
  'xsy': 'Saisiyat',
  'trv': 'Taroko',
  'tsu': 'Tsou',
  'bnn': 'Bunun',
  'pyu': 'Puyuma',
  'roa': 'Rukai',
  'knn': 'Konkani',
  
  // Constructed/Artificial Languages
  'eo': 'Esperanto',
  'ia': 'Interlingua',
  'ie': 'Interlingue',
  'vo': 'Volapük',
  'jbo': 'Lojban',
  'tlh': 'Klingon',
  'qya': 'Quenya',
  'sjn': 'Sindarin',
  'art': 'Artificial Language',
  
  // Historical/Ancient Languages
  'la': 'Latin',
  'grc': 'Ancient Greek',
  'got': 'Gothic',
  'non': 'Old Norse',
  'ang': 'Old English',
  'gmh': 'Middle High German',
  'fro': 'Old French',
  'osp': 'Old Spanish',
  'chu': 'Church Slavonic',
  'cop': 'Coptic',
  'egy': 'Egyptian (Ancient)',
  'hit': 'Hittite',
  'akk': 'Akkadian',
  'sux': 'Sumerian',
  'xbc': 'Bactrian',
  'xpr': 'Parthian',
  'pal': 'Middle Persian',
  'sog': 'Sogdian',
  'oui': 'Old Uyghur',
  'xto': 'Tocharian A',
  'txb': 'Tocharian B',
  
  // Sign Languages
  'sgn': 'Sign Language',
  'ase': 'American Sign Language',
  'bsl': 'British Sign Language',
  'fsl': 'French Sign Language',
  'gsg': 'German Sign Language',
  'jsl': 'Japanese Sign Language',
  'csl': 'Chinese Sign Language',
  'rsl': 'Russian Sign Language',
  'ins': 'Indian Sign Language',
  'bfi': 'British Sign Language',
  'bzs': 'Brazilian Sign Language',
  
  // Regional/Minority Languages
  'an': 'Aragonese',
  'ast': 'Asturian',
  'ext': 'Extremaduran',
  'mwl': 'Mirandese',
  'oc': 'Occitan',
  'pms': 'Piedmontese',
  'lmo': 'Lombard',
  'fur': 'Friulian',
  'lld': 'Ladin',
  'rgn': 'Romagnol',
  'egl': 'Emilian',
  'lij': 'Ligurian',
  'pcd': 'Picard',
  'nrm': 'Norman',
  'ksh': 'Kölsch',
  'pfl': 'Palatine German',
  'bar': 'Bavarian',
  'als': 'Alemannic',
  'gsw': 'Swiss German',
  'wym': 'Vilamovian',
  'szl': 'Silesian',
  'csb': 'Kashubian',
  'dsb': 'Lower Sorbian',
  'hsb': 'Upper Sorbian',
  'rue': 'Rusyn',
  'bel': 'Belarusian',
  
  // Australian Aboriginal Languages
  'aus': 'Australian Language',
  'arb': 'Arabic',
  'pjt': 'Pitjantjatjara',
  'wbp': 'Warlpiri',
  'gup': 'Gunwinggu',
  'yir': 'Yir Yoront',
  'kld': 'Gamilaraay',
  'wrk': 'Garrwa',
  'gyd': 'Kayardild',
  'dhg': 'Dhangu',
  'dbl': 'Dyirbal',
  'xul': 'Ngunawal',
  'nys': 'Nyunga',
  'adh': 'Adhola',
  'mpj': 'Martu Wangka',
  'wro': 'Worrorra',
  'gwm': 'Gooniyandi',
  'kdd': 'Yankunytjatjara'
};

/**
 * Converts a language code to its display name
 * @param {string} languageCode - ISO 639-1 language code
 * @returns {string} - Display name for the language
 */
export const getLanguageName = (languageCode) => {
  if (!languageCode) return 'Unknown';
  
  const code = languageCode.toLowerCase();
  return LANGUAGE_MAPPING[code] || languageCode.toUpperCase();
};

/**
 * Gets all unique languages from movies and returns them with proper names
 * @param {Array} movies - Array of movie objects
 * @returns {Array} - Array of objects with code and name properties
 */
export const getLanguagesWithNames = (movies) => {
  if (!Array.isArray(movies)) return [];
  
  const languageCodes = movies
    .map(movie => movie.language || movie.original_language || 'en')
    .filter(Boolean)
    .filter((value, index, self) => self.indexOf(value) === index)
    .sort();
  
  return languageCodes.map(code => ({
    code,
    name: getLanguageName(code)
  })).sort((a, b) => a.name.localeCompare(b.name));
};